package jaiz.grandadventure.entity.animation;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class GradstoneGuardianAnimations{

public static final Animation GRANDSTONE_GAURDIAN_WALK = Animation.Builder.create(1f).looping()
        .addBoneAnimation("leg_l",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0.25f, 0f, -3f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0.25f, 0f, 2f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createTranslationalVector(-0.25f, 3f, 2f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0.25f, 3f, -3f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(0.25f, 0f, -3f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg_l",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createRotationalVector(-7.5f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg_r",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(-0.25f, 3f, 2f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createTranslationalVector(-0.25f, 3f, -3f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createTranslationalVector(-0.25f, 0f, -3f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createTranslationalVector(-0.25f, 0f, 2f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(-0.25f, 3f, 2f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg_r",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(-7.5f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(-7.5f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("body",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("arm_l2",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("arm_l2",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -90f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("arm_r2",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("arm_r2",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 90f),
                                Transformation.Interpolations.LINEAR))).build();

public static final Animation GRANDSTONE_GUARDIAN_ATTACK = Animation.Builder.create(1f).looping()
        .addBoneAnimation("arm_l",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 1f, 5f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, 0f, -3f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(0f, 0f, -4f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("arm_l",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(-360f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("arm_l2",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("arm_l2",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -90f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, -90f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, -90f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, -90f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("arm_r",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 1f, 5f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, 0f, -3f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(0f, 0f, -5f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("arm_r",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(-360f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("arm_r2",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("arm_r2",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 90f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 90f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 90f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 90f),
                                Transformation.Interpolations.LINEAR))).build();
}
